# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: training_example.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='training_example.proto',
  package='super_resolution',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16training_example.proto\x12\x10super_resolution\"9\n\x0fTrainingExample\x12\x0e\n\x06\x66rames\x18\x01 \x03(\x0c\x12\x16\n\x0ehigh_res_frame\x18\x02 \x01(\x0c\"G\n\x10TrainingExamples\x12\x33\n\x08\x65xamples\x18\x01 \x03(\x0b\x32!.super_resolution.TrainingExampleb\x06proto3'
)




_TRAININGEXAMPLE = _descriptor.Descriptor(
  name='TrainingExample',
  full_name='super_resolution.TrainingExample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frames', full_name='super_resolution.TrainingExample.frames', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='high_res_frame', full_name='super_resolution.TrainingExample.high_res_frame', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=101,
)


_TRAININGEXAMPLES = _descriptor.Descriptor(
  name='TrainingExamples',
  full_name='super_resolution.TrainingExamples',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='examples', full_name='super_resolution.TrainingExamples.examples', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=174,
)

_TRAININGEXAMPLES.fields_by_name['examples'].message_type = _TRAININGEXAMPLE
DESCRIPTOR.message_types_by_name['TrainingExample'] = _TRAININGEXAMPLE
DESCRIPTOR.message_types_by_name['TrainingExamples'] = _TRAININGEXAMPLES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrainingExample = _reflection.GeneratedProtocolMessageType('TrainingExample', (_message.Message,), {
  'DESCRIPTOR' : _TRAININGEXAMPLE,
  '__module__' : 'training_example_pb2'
  # @@protoc_insertion_point(class_scope:super_resolution.TrainingExample)
  })
_sym_db.RegisterMessage(TrainingExample)

TrainingExamples = _reflection.GeneratedProtocolMessageType('TrainingExamples', (_message.Message,), {
  'DESCRIPTOR' : _TRAININGEXAMPLES,
  '__module__' : 'training_example_pb2'
  # @@protoc_insertion_point(class_scope:super_resolution.TrainingExamples)
  })
_sym_db.RegisterMessage(TrainingExamples)


# @@protoc_insertion_point(module_scope)
